{{/*
=============================================================================
IBM webMethods Hybrid Integration (IWHI) – Helm Helper Templates
=============================================================================
*/}}

{{/*
Expand the chart name.
*/}}
{{- define "apic.name" -}}
{{- .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Resolve the target namespace.
*/}}
{{- define "apic.namespace" -}}
{{- .Values.global.namespace }}
{{- end }}

{{/*
Resolve the image registry for a subsystem.
Falls back to global.imageRegistry if the subsystem-level value is empty.
Usage: {{ include "apic.imageRegistry" (dict "subsystem" .Values.wmapigateway "global" .Values.global) }}
*/}}
{{- define "apic.imageRegistry" -}}
{{- if .subsystem.imageRegistry -}}
{{- .subsystem.imageRegistry -}}
{{- else -}}
{{- .global.imageRegistry -}}
{{- end -}}
{{- end }}

{{/*
Resolve the storage class for a subsystem.
Falls back to global.storageClass if the subsystem-level value is empty.
Usage: {{ include "apic.storageClass" (dict "subsystem" .Values.management "global" .Values.global) }}
*/}}
{{- define "apic.storageClass" -}}
{{- if .subsystem.storageClass -}}
{{- .subsystem.storageClass -}}
{{- else -}}
{{- .global.storageClass -}}
{{- end -}}
{{- end }}

{{/*
Resolve the analytics ref namespace for a subsystem.
Falls back to global.namespace if the analyticsRef.namespace value is empty.
Usage: {{ include "apic.analyticsRefNamespace" (dict "ref" .Values.devportal.analyticsRef "global" .Values.global) }}
*/}}
{{- define "apic.analyticsRefNamespace" -}}
{{- if .ref.namespace -}}
{{- .ref.namespace -}}
{{- else -}}
{{- .global.namespace -}}
{{- end -}}
{{- end }}

{{/*
Common labels applied to every resource.
*/}}
{{- define "apic.labels" -}}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: ibm-apiconnect
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}

{{/*
Resolve the certificate issuer name.
Returns the provided name if set, otherwise returns the default created issuer name.
Usage: {{ include "apic.issuerName" . }}
*/}}
{{- define "apic.issuerName" -}}
{{- if .Values.certificates.issuer.name -}}
{{- .Values.certificates.issuer.name -}}
{{- else -}}
apic-issuer
{{- end -}}
{{- end }}

{{/*
Resolve the certificate issuer kind.
Usage: {{ include "apic.issuerKind" . }}
*/}}
{{- define "apic.issuerKind" -}}
{{- .Values.certificates.issuer.kind -}}
{{- end }}

{{/*
Determine if issuer should be created.
Returns true if name is empty (meaning we need to create it).
Usage: {{ include "apic.createIssuer" . }}
*/}}
{{- define "apic.createIssuer" -}}
{{- if not .Values.certificates.issuer.name -}}
true
{{- end -}}
{{- end }}

{{/*
Resolve the cert-manager annotation key for the issuer.
Returns "cert-manager.io/cluster-issuer" if kind is ClusterIssuer, otherwise "cert-manager.io/issuer".
Usage: {{ include "apic.issuerAnnotation" . }}
*/}}
{{- define "apic.issuerAnnotation" -}}
{{- if eq (include "apic.issuerKind" .) "ClusterIssuer" -}}
cert-manager.io/cluster-issuer
{{- else -}}
cert-manager.io/issuer
{{- end -}}
{{- end }}

{{/*
Name of the ValkeyCluster CR (and its leader service) deployed by this chart.
*/}}
{{- define "apic.valkeyClusterName" -}}
valkey
{{- end }}

{{/*
Render an auto-generated Opaque Secret containing a random password, reusing
the existing value on upgrades via `lookup` so dependent CRs are never
recreated with a mismatched password.
Usage: {{ include "apic.autoGeneratedSecret" (dict "root" . "name" "my-secret" "key" "password") }}
*/}}
{{- define "apic.autoGeneratedSecret" -}}
{{- $root := .root }}
{{- $ns := include "apic.namespace" $root }}
{{- $secretName := .name }}
{{- $secretKey := .key }}
{{- $existing := lookup "v1" "Secret" $ns $secretName }}
{{- $password := "" }}
{{- if $existing }}
{{- $password = index $existing.data $secretKey | b64dec }}
{{- else }}
{{- $password = randAlphaNum 16 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "apic.labels" $root | nindent 4 }}
type: Opaque
data:
  {{ $secretKey }}: {{ $password | b64enc }}
{{- end }}

{{/*
Resolve the Nano Gateway Redis host.
Falls back to the in-chart ValkeyCluster leader service if nanogateway.redis.host is empty.
Usage: {{ include "apic.nanogatewayRedisHost" . }}
*/}}
{{- define "apic.nanogatewayRedisHost" -}}
{{- if .Values.nanogateway.redis.host -}}
{{- .Values.nanogateway.redis.host -}}
{{- else -}}
{{- printf "%s-leader.%s.svc.cluster.local" (include "apic.valkeyClusterName" .) (include "apic.namespace" .) -}}
{{- end -}}
{{- end }}
